this is a basic program that introduces me to numpy

temperature, rainfall and humidity data for the below regions
kanto= 73,67,43
johto=91,88,64
we are going to create a vector rather than creating new variables for each and every region and we will also define weights and create a function
the function will provide realtion between the factors and weights therby providing information about the yield

In [15]:
kanto=[73,67,43]
johto=[91,88,64]

In [10]:
w1=0.3
w2=0.2
w3=0.5

In [11]:
weights=[w1,w2,w3]

In [18]:
def calc_yield(region,weights):
    result=0
    for x,w in zip(region,weights):
        result+=x*w
    return result

In [19]:
calc_yield(kanto,weights)

56.8

In [2]:
!pip install numpy

In [3]:
import numpy as np

In [4]:
kanto=np.array([73,67,43])
weights=np.array([0.3,0.2,0.5])

#here we are using the .item() function to get the value of the result else we will also get float64 before the result that is not an error it just shows the datatype of the result

In [6]:
np.dot(kanto,weights).item()

56.8

In [7]:
arr1=list(range(1000000))
arr2=list(range(1000000,2000000))

np_arr1=np.array(arr1)
np_arr2=np.array(arr2)

In [12]:
%%time
result=0
for x,y in zip(arr1,arr2):
    result+=x*y
print(result)

833332333333500000
CPU times: total: 391 ms
Wall time: 404 ms


In [14]:
%%time
np.dot(np_arr1,np_arr2).item()

CPU times: total: 0 ns
Wall time: 1.22 ms


833332333333500000

In [ ]:
# we can also create a 2d array to reduce steps and simplify calculations 

In [2]:
import numpy as np

In [4]:
climate_data=np.array([[73,67,43],
                       [54,35,86],
                       [45,28,72],
                       [86,25,19],
                       [59,47,68]])

In [6]:
climate_data

array([[73, 67, 43],
       [54, 35, 86],
       [45, 28, 72],
       [86, 25, 19],
       [59, 47, 68]])

In [7]:
climate_data.shape

(5, 3)

In [ ]:
# the above cell shows that with the use of the 'shape' function we can find the dimensions of a given matrix

In [12]:
weights

[0.3, 0.2, 0.5]

In [ ]:
# below we are using the 'matmul' function to compute the matrix multiplication

In [13]:
np.matmul(climate_data,weights)

array([56.8, 66.2, 55.1, 40.3, 61.1])

In [ ]:
# we can also use '@' for the same

In [14]:
climate_data @ weights

array([56.8, 66.2, 55.1, 40.3, 61.1])

In [ ]:
# we can use the '.dtytpe' function to find the datatype of the numpy array

In [16]:
climate_data.dtype

dtype('int64')