In [1]:
import numpy as np

In [4]:
climate_data=np.genfromtxt("climate.txt",delimiter=",",skip_header=1)

In [5]:
climate_data

array([[ 24.15, 424.89,  22.54],
       [ 15.09,  13.35,  15.16],
       [ 40.43,  73.67,  59.19],
       ...,
       [ 10.41, 422.56,  66.36],
       [ 10.52, 358.27,  96.58],
       [ 11.24, 282.47,  32.77]], shape=(10000, 3))

In [6]:
climate_data.shape

(10000, 3)

In [7]:
w1,w2,w3=0.3,0.2,0.5

In [8]:
weights=w1,w2,w3

In [9]:
weights

(0.3, 0.2, 0.5)

In [10]:
yield_apples = climate_data @ weights

In [11]:
yield_apples

array([103.493,  14.777,  56.458, ..., 120.815, 123.1  ,  76.251],
      shape=(10000,))

In [13]:
climate_results=np.concatenate((climate_data,yield_apples.reshape(10000,1)),axis=1)

In [14]:
climate_results

array([[ 24.15 , 424.89 ,  22.54 , 103.493],
       [ 15.09 ,  13.35 ,  15.16 ,  14.777],
       [ 40.43 ,  73.67 ,  59.19 ,  56.458],
       ...,
       [ 10.41 , 422.56 ,  66.36 , 120.815],
       [ 10.52 , 358.27 ,  96.58 , 123.1  ],
       [ 11.24 , 282.47 ,  32.77 ,  76.251]], shape=(10000, 4))

In [16]:
np.savetxt('climate_results.txt',
           climate_results,
           fmt='%.2f',
           header='temperature,rainfall,humidity,yield_of_apples',
           comments=' ')